### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by nzrin** [xander18/MapBoxShowDirection#1]
I've tried to run your project using my token and location but failed..

``` Index : 1, Size : 0 ``` 

Please help

**Comment by xander18** [comment]
Hi m8 tell me did u followed thoses instructions :
What you need to add :

const accessToken = 'YOUR_ACCESS_TOKEN'; // put your access token here

const UserLocation = []; // [longitude, latitude] Coord of the location where you want to put the user

const StartLocation = UserLocation; // by default userLocation but you can put different coord here

const DestinationLocation = []; // [longitude, latitude] Coord of your destination

**Comment by xander18** [comment]
> I've tried to run your project using my token and location but failed..
> 
> `Index : 1, Size : 0`
> 
> Please help

Up

**Comment by xander18** [comment]
Fixed
