### ISSUE TITLE
Example without using Hooks.

### ISSUE THREAD

**Issue by nzrin** [xander18/MapBoxShowDirection#3]
Hi, can you provide sample .js file without using hooks? Perhaps like this using class :

```class MapBoxShowDirection extends Component {```

Please?

**Comment by xander18** [comment]
i'll find some time this week to make it

**Comment by xander18** [comment]
> Hi, can you provide sample .js file without using hooks? Perhaps like this using class :
> 
> `class MapBoxShowDirection extends Component {`
> 
> Please?

reming me this week i'll got the time to make it sorry for the late answer i was overbooked

**Comment by nzrin** [comment]
Okay sure.

**Comment by xander18** [comment]
> Okay sure.

i pushed as asked a Class Component called AppClass.js just replace in index the import by AppClass instead of App

**Comment by nzrin** [comment]
I've tried this code without hooks but it doesnt work. It seems drawPath doesn't even triggered. Please help.

**Comment by Polyrion** [comment]
> I've tried this code without hooks but it doesnt work. It seems drawPath doesn't even triggered. Please help.

@nzrin could you show me your code or join the discord https://discord.gg/vBBBgW
thx u
